[package]
name = "rtmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corncobs = "0.1.3"
serial2 = "0.2.21"
